{% set version = "0.1.1" %}

package:
  name: geoana
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoana/geoana-{{ version }}.tar.gz
  sha256: 7721af36238a8d44667fc9fd0904c5577ac19df1a8b43498071672aee21dcbd5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future
    - matplotlib-base
    - numpy >=1.7
    - properties
    - vectormath
    - scipy >=0.13
    - utm

test:
  imports:
    - geoana
    - geoana.earthquake
    - geoana.em

about:
  home: https://www.simpeg.xyz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interactive geoscience (mostly) analytic functions.

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
