{% set version = "0.2.3" %}

package:
  name: geoana
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoana/geoana-{{ version }}.tar.gz
  sha256: 8bc894933473fe59f26246412d0a863fdebe1776af6da87bf280d227552c3e64

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy >=1.8
    - cython >=0.2
  run:
    - python
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13
    - utm
    - empymod

test:
  imports:
    - geoana
    - geoana.earthquake
    - geoana.em
    - geoana.kernels._extensions

about:
  home: https://www.simpeg.xyz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interactive geoscience (mostly) analytic functions.

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
