{% set version = "0.4.1" %}

package:
  name: geoana
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoana/geoana-{{ version }}.tar.gz
  sha256: bd94df5be307f3e7b6ca4b2abc8475576c9835102245e577dfdaebca0a04260b

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy >=1.8
    - cython >=0.2
  run:
    - python
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13
    - utm
    - empymod >=2.0

test:
  imports:
    - geoana
    - geoana.earthquake
    - geoana.em
    - geoana.kernels._extensions

about:
  home: https://www.simpeg.xyz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interactive geoscience (mostly) analytic functions.

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
