{% set version = "0.6.0" %}

package:
  name: geoana
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoana/geoana-{{ version }}.tar.gz
  sha256: 4e889997b18ccbfe42e37964e90cdba2418c4cc4d4f2e45e441c47c4a192bcab

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - cython >=0.29
    - setuptools_scm
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.8
    - libdlf

test:
  imports:
    - geoana
    - geoana.earthquake
    - geoana.em
    - geoana.kernels._extensions

about:
  home: https://www.simpeg.xyz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interactive geoscience (mostly) analytic functions.

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
