{% set version = "0.0.6" %}

package:
  name: geoana
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoana/geoana-{{ version }}.tar.gz
  sha256: 7f37a72a722f5f0690fdefe0cbafc59d613143962e154c87210a0b4f6d1d3730

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future
    - matplotlib-base
    - numpy >=1.7
    - properties
    - vectormath
    - scipy >=0.13
    - utm

test:
  imports:
    - geoana
    - geoana.earthquake
    - geoana.em

about:
  home: https://www.simpeg.xyz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interactive geoscience (mostly) analytic functions.

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
