{% set version = "0.7.0_rc" %}

package:
  name: geoana
  version: {{ version }}

source:
  git_url: https://github.com/simpeg/geoana.git
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: 0
  skip: true  # [py<310]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - ninja                                  # [unix]
    - pkg-config                             # [unix]
  host:
    - python
    - python-build
    - pip
    - cython >=0.29.35,!=3.0.3
    - meson-python
    - numpy
    - setuptools_scm
  run:
    - python
    - numpy
    - scipy >=1.8
    - libdlf

test:
  imports:
    - geoana
    - geoana.earthquake
    - geoana.em
    - geoana.kernels._extensions

about:
  home: https://www.simpeg.xyz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interactive geoscience (mostly) analytic functions.

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
