{% set version = "0.1.3" %}

package:
  name: geoana
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoana/geoana-{{ version }}.tar.gz
  sha256: 25931d341b075a5c99c4e2421cfcf3f0083ac990ca99ac40fdd405b21f6c7971

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy >=1.8
    - cython >=0.2
  run:
    - python
    - future
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - properties
    - vectormath
    - scipy >=0.13
    - utm
    - empymod

test:
  imports:
    - geoana
    - geoana.earthquake
    - geoana.em
    - geoana.kernels._extensions

about:
  home: https://www.simpeg.xyz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interactive geoscience (mostly) analytic functions.

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
