travis:
  secure:
    BINSTAR_TOKEN: zNQv63TcujIwe0Y5UuRiq9g1UTu7jWHgAzB13s7AsECoDRAwnwXcDaH7CTSyoZDsnilvDNMb778j+qLP6JO7KL1uO6Crf9WgBcfXShxEZL9O8c375NqVcawy3fRtcKniTj7YHuPVvFA/DtN13P2lohAEOabllCKAF7oCj5wip3+uZK9uHHODefugp8hrSWl+tojQ+AOP5jXVqBTWzYctQUJ9hb/ty4YH+MjYoWbNttpB100qlNk9ZAVizdzRAg9fMLT4V4tGgk55oerWKQAis83cLO79ldiLFwFbhaoZcx4/CzjYiL4NVZ0d+afR7BuWNsvkKZpGv6ptesc6pssBHLjko78k3OeDTivWg6qHmFTJUSor0V3aWpQzhHICPYluNSA2crQf2i4BRj6z7uIMPd+amo80yZyW3Rjzso9XEglCT4rnOUZaM/TK7rRmo/sEVITCVivA7CzKl3IxvWySSnuvNElHKuMAc79wWwmkq1B9Ahe24qav51PQL0yGmsfQ64YAdtUbbhcLxeH+9Uw6em8DqT7wF3Fr7x4ShBvsJEFSExNvG8b9U4Ui8dRvKS48MphVLNXuTK7F3VoSwBT3Y4WIPiDiEnDKM1nP9WdlyNmSE/WKiGJ8CPySwk5SADmzyMK9uDgKXCB66X+Q8oT0exZWuwBCFQvVJR4aKafmFRM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
